# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmPoints2One.ui'
#
# Created: Mon May 17 09:38:58 2010
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(402, 375)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.widget = QtGui.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(9, 9, 391, 351))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.vboxlayout = QtGui.QVBoxLayout()
        self.vboxlayout.setObjectName("vboxlayout")
        self.label_1 = QtGui.QLabel(self.widget)
        self.label_1.setObjectName("label_1")
        self.vboxlayout.addWidget(self.label_1)
        self.inShape = QtGui.QComboBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inShape.sizePolicy().hasHeightForWidth())
        self.inShape.setSizePolicy(sizePolicy)
        self.inShape.setObjectName("inShape")
        self.vboxlayout.addWidget(self.inShape)
        self.gridLayout_2.addLayout(self.vboxlayout, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.rdoPolygon = QtGui.QRadioButton(self.groupBox)
        self.rdoPolygon.setChecked(True)
        self.rdoPolygon.setAutoRepeat(False)
        self.rdoPolygon.setObjectName("rdoPolygon")
        self.verticalLayout.addWidget(self.rdoPolygon)
        self.rdoPolyline = QtGui.QRadioButton(self.groupBox)
        self.rdoPolyline.setChecked(False)
        self.rdoPolyline.setAutoRepeat(False)
        self.rdoPolyline.setObjectName("rdoPolyline")
        self.verticalLayout.addWidget(self.rdoPolyline)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rdoKeyName = QtGui.QRadioButton(self.widget)
        self.rdoKeyName.setAutoExclusive(False)
        self.rdoKeyName.setObjectName("rdoKeyName")
        self.verticalLayout_2.addWidget(self.rdoKeyName)
        self.attrName = QtGui.QComboBox(self.widget)
        self.attrName.setEnabled(False)
        self.attrName.setObjectName("attrName")
        self.verticalLayout_2.addWidget(self.attrName)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.vboxlayout1.addWidget(self.label_5)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.outShape = QtGui.QLineEdit(self.widget)
        self.outShape.setReadOnly(True)
        self.outShape.setObjectName("outShape")
        self.hboxlayout.addWidget(self.outShape)
        self.btnBrowse = QtGui.QPushButton(self.widget)
        self.btnBrowse.setObjectName("btnBrowse")
        self.hboxlayout.addWidget(self.btnBrowse)
        self.vboxlayout1.addLayout(self.hboxlayout)
        self.gridLayout_2.addLayout(self.vboxlayout1, 4, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressBar = QtGui.QProgressBar(self.widget)
        self.progressBar.setProperty("value", QtCore.QVariant(0))
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.buttonBox_2 = QtGui.QDialogButtonBox(self.widget)
        self.buttonBox_2.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_2.setObjectName("buttonBox_2")
        self.horizontalLayout.addWidget(self.buttonBox_2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 5, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox_2, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QObject.connect(self.buttonBox_2, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.rdoKeyName, QtCore.SIGNAL("toggled(bool)"), self.attrName.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Points2One", None, QtGui.QApplication.UnicodeUTF8))
        self.label_1.setText(QtGui.QApplication.translate("Dialog", "Input point layer", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Points to one", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoPolygon.setText(QtGui.QApplication.translate("Dialog", "Polygon", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoPolyline.setText(QtGui.QApplication.translate("Dialog", "Polyline", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Multiple processing", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoKeyName.setText(QtGui.QApplication.translate("Dialog", "Create output features based on input field ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Output shapefile", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowse.setText(QtGui.QApplication.translate("Dialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))

